# Generated by Django 5.1.6 on 2025-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='igmodel',
            name='sender',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
